name: build

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v3
      - run: |
          docker build -f bin/Dockerfile \
            --build-arg PYTHON_VERSION=${{ matrix.python-version }} \
            --tag minari-docker .
      - name: Run tests
        run: docker run minari-docker pytest tests/* -k "not test_docs.py and not integrations"
