# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
---
name: Tutorial tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  tutorial-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
        tutorial: ['LocalStorage', 'RemoteStorage', 'DatasetUsage', 'DatasetCreation']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies and run tutorials
        env:
          GCP_DATASET_ADMIN: ${{ secrets.GCP_DATASET_ADMIN }}
        run: |
          cd tutorials/${{ matrix.tutorial }}
          pip install -r requirements.txt
          pip uninstall -y minari
          pip install -e ../..
          for f in *.py; do python "$f"; done
