name: test integrations

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          docker build -f bin/Dockerfile \
            --build-arg PYTHON_VERSION=3.11 \
            --tag minari-docker .
      - name: Run tests
        run: docker run minari-docker pytest tests/integrations
